### ISSUE TITLE
Auto zoom and fit to shape file location

### ISSUE THREAD

**Issue by srijitcoder** [blueskyanalytics/raster-playground#12]
Right now when we load shapefiles it's view is at a low zoom level... We need to auto-zoom and fit it's bound to that shapefile location

### Current View (low zoom level and away from shapefile view) -
![image](https://user-images.githubusercontent.com/10809211/102486305-db143380-408e-11eb-88b6-4a9016492233.png)

### Desired View (auto zoomed and in correct position of shapefile) - 
![image](https://user-images.githubusercontent.com/10809211/102486501-22022900-408f-11eb-900d-2271fd5dd173.png)

**Comment by Sahil004** [comment]
PR: #21
Preview: https://deploy-preview-21--raster-playground.netlify.app/

**Comment by abhinav2422** [comment]
PR: #23 
Netlify Preview: https://deploy-preview-23--raster-playground.netlify.app/

Also completed issue #17
