### ISSUE TITLE
A small search bar

### ISSUE THREAD

**Issue by srijitcoder** [blueskyanalytics/raster-playground#16]
A small search bar to fly to a new location on map **(For easy accessibility)**

#### Like - You can search location on https://geojson.io/
![image](https://user-images.githubusercontent.com/10809211/102491542-5b8a6280-4096-11eb-93e3-b9c190224c2c.png)

**Comment by tikeshisverma** [comment]
Hi @srijitcoder, I have raised a PR fixing this issue. Please let me know if it requires any change.
