### ISSUE TITLE
Convert `Alpha Value` input field into slider

### ISSUE THREAD

**Issue by srijitcoder** [blueskyanalytics/raster-playground#64]
### Context 
Right now, users are only able to enter `Alpha values` inside a numerical input field.

### Problem 
It gets challenging to enter the numerical value every time into the input field. And user's don't even know they can enter decimal values too between (0-1). This affects the UX of RP. 

### Solution 
- Make a draggable slider for `Alpha value`
- Min value will be `0`
- Max value will be `1`
- In between `min` and `max` value will be in 2 decimal point float `0 < x < 1` (eg - `x = 0.35`)
- Also add a small textual input field along with a slider

![image](https://user-images.githubusercontent.com/10809211/136201588-41e171ee-63b7-4a3e-8a4a-a208126c0350.png)

**Comment by LeaFranz** [comment]
@srijitcoder Where should the input field be placed?

**Comment by srijitcoder** [comment]
> @srijitcoder Where should the input field be placed?

### Here - You need to add a slider along with a small square input field 

<img width="1680" alt="Screenshot 2021-10-06 at 10 33 45 PM" src="https://user-images.githubusercontent.com/10809211/136250593-eeefa407-d31d-4818-a946-65d771aa16f3.png">

**Comment by LeaFranz** [comment]
@srijitcoder I would like to try this, could you assign this to me? :)

**Comment by LeaFranz** [comment]
@srijitcoder Could you please also tag the project with 'hacktoberfest' so that my pull request counts towards it?

**Comment by srijitcoder** [comment]
Accepted PR #65

**Comment by srijitcoder** [comment]
Accepted PR #65
