### ISSUE TITLE
Color Output Box improvements

### ISSUE THREAD

**Issue by kshitijpurwar** [blueskyanalytics/raster-playground#8]
- Add button to copy it all

- Prettier formatting of color codes

- Available in CSV, hex codes, JSON, RGBA etc

**Comment by richachauhan59** [comment]
May I get a example of using Prettier on the color code, I am able to achive this, but it seems to be too lengthy:

[
  {
    "r": 241,
    "g": 238,
    "b": 246,
    "a": 255
  },
  {
    "r": 228,
    "g": 210,
    "b": 231,
    "a": 255
  },
  {
    "r": 215,
    "g": 181,
    "b": 216,
    "a": 255
  },
  {
    "r": 219,
    "g": 141,
    "b": 196,
    "a": 255
  },
  {
    "r": 223,
    "g": 101,
    "b": 176,
    "a": 255
  },
  {
    "r": 51,
    "g": 40,
    "b": 46,
    "a": 255
  },
  {
    "r": 221,
    "g": 28,
    "b": 119,
    "a": 255
  },
  {
    "r": 187,
    "g": 14,
    "b": 93,
    "a": 255
  },
  {
    "r": 152,
    "g": 0,
    "b": 67,
    "a": 255
  }
]
